### ISSUE TITLE
Change default behaviour of `ignore_download_error` to false

### ISSUE THREAD

**Issue by rhtenhove** [stablestud/adsorber#11]
The default behaviour is to ignore download errors. In my (quite regular) setup this causes adsorber to not apply anything, because it runs at system startup with systemd, and the wifi doesn't connect that fast.
This results in an empty hosts file, and thus nothing gets blocked except for what's on the blacklist.

When setting `ignore_download_error=false` in `/usr/local/etc/adsorber/adsorber.conf`, it still proceeds after a download error when running `adsorber update`. So it seems the setting is ignored either way.

**Comment by stablestud** [comment]
Hello rhtenhove,

Thanks for reporting!

Sorry for being late, been on vacation.

I could reproduce your issue, im onto fixing it.
Also I will change the default `ignore_download_error` to `false` as you suggested, because it makes more sense actually.

Cheers
stablestud
