### ISSUE TITLE
Unable to install onto system - WGet error

### ISSUE THREAD

**Issue by Voralberg** [stablestud/adsorber#26]
Trying to install this utility (Placing file onto system) under **Fedora 40** I have encauntered a problem caused by **wget** that doesn't recognize the option 'show-progress'. Here's the entire terminal output of a clean install:

```
Reading configuration ...
Setting up Adsorber ...
> Do you really want to setup Adsorber? [Y/n]: y
  Successfully created backup of /etc/hosts to /etc/hosts.original.
> What scheduler should be used to update the host file automatically? [(C)ron/(s)ystemd/(n)one]: s
> How often should the service run? [(h)ourly/(d)aily/(W)eekly/(m)onthly/(q)uarterly]: d
  Setting up daily Systemd service ...
  Initialized Systemd service ...
Updating /etc/hosts ...
  Getting: https://adaway.org/hosts.txt
  Unknown option 'show-progress'
! wget couldn't fetch: https://adaway.org/hosts.txt
  Getting: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  Unknown option 'show-progress'
! wget couldn't fetch: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
! Couldn't fetch all hosts sources [0/2]. Aborting ...
! Cleaning up ...
  Removed Adsorber's Systemd service.
  Removed backup as the setup failed.
```

Uninstalling _wget_, and thus automatically using _curl_ solves the issue although it's not always possible to uninstall _wget_ due to some dependencies. Is there a way to force the use of _curl_?

In any case I would also like to thank the developer behind this utility, I can't have a system without it!

P.S. The latest version of wget at the moment on Fedora 40 is the **GNU Wget2 2.1.0**.

**Comment by stablestud** [comment]
@Voralberg what Adsorber version do you use?

I released yesterday a new version v1.0.2 which adds support for wget2 :)

**Comment by stablestud** [comment]
Could you please try and verify if its working for you with the latest version? (v.1.0.2)

**Comment by Voralberg** [comment]
I'm sorry, my bad, I really didn't noticed the released update. I have installed the new version, added StevenBlack's host file as a source, updated and rebooted. Everything works flawlessly! 
Thank you again for your work.
